# Generated by Django 6.1.1 on 2026-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.CharField(max_length=110, verbose_name='Электронная почта')),
                ('policy', models.BooleanField(default=False, verbose_name='Согласие на обработку')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=250, verbose_name='ФИО')),
                ('city', models.CharField(max_length=120, verbose_name='Муниципальное образование')),
                ('place', models.TextField(verbose_name='Площадка, которую хотите посетить')),
                ('format', models.CharField(blank=True, choices=[('off', 'Очно'), ('onn', 'Заочно')], max_length=3, null=True, verbose_name='Формат участия')),
                ('message', models.TextField(verbose_name='Доп. информация для организаторов')),
                ('policy', models.BooleanField(default=False, verbose_name='Согласие на обработку')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрационные заявки',
            },
        ),
    ]
