# Generated by Django 6.1.1 on 2026-09-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='category',
            field=models.CharField(choices=[('youngfamily', 'Молодая семья'), ('manyfamily', 'Многодетная семья'), ('studyfamily', 'Студенческая семья'), ('invalidfamily', 'Семья, воспитывающая ребенка инвалида, ребенка с ограниченными возможностями здоровья'), ('zameshaushie', 'Замещающая семья (опекуны, попечители, приемные родители и усыновители)'), ('kandidatzamesh', 'Кандидаты в замещающие семьи (слушатели школы приемных родителей)'), ('regorganspred', 'Представитель региональных и муниципальных органов государственной власти'), ('peoplepred', 'Представитель общественной организации'), ('healthpred', 'Представитель организации здравоохранения'), ('studypred', 'Представитель образовательной организации'), ('socialpred', 'Представитель организации социального обслуживания'), ('culturepred', 'Представитель организации культуры'), ('sportpred', 'Представитель организации физической культуры и спорта'), ('study', 'Студент'), ('volonteer', 'Волонтер'), ('another', 'Другое')], default=1, max_length=15, verbose_name='Категория участника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(default=1, max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.CharField(default=1, max_length=30, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(choices=[('belraion', 'Белоярский район'), ('berezraion', 'Берёзовский район'), ('kondraion', 'Кондинский район'), ('neftraion', 'Нефтеюганский район'), ('nijneraion', 'Нижневартовский район'), ('oktybrraion', 'Октябрьский район'), ('sovetraion', 'Советский район'), ('surgutraion', 'Сургутский район'), ('khantyraion', 'Ханты-Мансийский район'), ('kogalym', 'Когалым'), ('langepas', 'Лангепас'), ('megion', 'Мегион'), ('neftegansk', 'Нефтеюганск'), ('nijnevartovsk', 'Нижневартовск'), ('nyagan', 'Нягань'), ('pokachi', 'Покачи'), ('pytyach', 'Пыть-Ях'), ('radujnyi', 'Радужный'), ('surgut', 'Сургут'), ('yrai', 'Урай'), ('khanty', 'Ханты-Мансийск'), ('ugorsk', 'Югорск')], max_length=15, verbose_name='Муниципальное образование'),
        ),
        migrations.AlterField(
            model_name='register',
            name='format',
            field=models.CharField(choices=[('off', 'Очно'), ('onn', 'Заочно')], default=1, max_length=3, verbose_name='Формат участия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='place',
            field=models.CharField(choices=[('prozvet', 'Проектная мастерская «Процветание»'), ('history', 'Проектная мастерская «История»'), ('inklusion', 'Проектная мастерская «Инклюзия»'), ('family', 'Проектная мастерская  «Семья»'), ('mir', 'Проектная мастерская «Мир»'), ('laboratory', 'Проектная мастерская «Лаборатория»'), ('iniciativa', 'Проектная мастерская «Инициатива»')], max_length=20, verbose_name='Площадка, которую хотите посетить'),
        ),
    ]
