# Generated by Django 6.1.1 on 2026-09-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_register_category_register_email_register_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='place',
            field=models.CharField(choices=[('prozvet', 'Лаборатория «Здоровье семьи – здоровье нации»'), ('history', 'Лаборатория «Социальная безопасность семьи и детства»'), ('inklusion', 'Лаборатория «Развитие родительских компетенций»')], max_length=20, verbose_name='Площадка, которую хотите посетить'),
        ),
    ]
