# Generated by Django 6.1.1 on 2026-09-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_register_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Доп. информация для организаторов'),
        ),
    ]
