# Generated by Django 6.1.1 on 2026-09-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_register_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.TextField(default=1, verbose_name='Текст сообщения'),
            preserve_default=False,
        ),
    ]
