# Generated by Django 6.1.1 on 2026-10-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_feedback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='category',
            field=models.CharField(choices=[('youngfamily', 'Молодая семья'), ('manyfamily', 'Многодетная семья'), ('studyfamily', 'Семья участника специальной военной операции'), ('invalidfamily', 'Семья, воспитывающая ребенка инвалида, ребенка с ограниченными возможностями здоровья'), ('zameshaushie', 'Замещающая семья (опекуны, попечители, приемные родители и усыновители)'), ('kandidatzamesh', 'Кандидаты в замещающие семьи (слушатели школы приемных родителей)'), ('regorganspred', 'Представитель региональных и муниципальных органов государственной власти'), ('peoplepred', 'Представитель общественной организации'), ('healthpred', 'Представитель организации здравоохранения'), ('studypred', 'Представитель образовательной организации'), ('socialpred', 'Представитель организации социального обслуживания'), ('culturepred', 'Представитель организации культуры'), ('sportpred', 'Представитель организации физической культуры и спорта'), ('study', 'Студент'), ('volonteer', 'Волонтер'), ('another', 'Другое')], max_length=15, verbose_name='Категория участника'),
        ),
    ]
